backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "cards"
    label: "Karten"
    files:
      - file: "data/cards.json"
        label: "Kartenliste"
        name: "cards"
        fields:
          - label: "Cards"
            name: "cards"
            widget: "list"
            fields:
              - {label: "Titel", name: "title", widget: "string"}
              - {label: "Text", name: "text", widget: "text"}